// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function DomReady(arg1:context.Context):Promise<void>;

export function GetServerUrl():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectImageFile():Promise<string>;

export function SelectMultipleImageFile():Promise<string>;

export function ShowDownloadImageDialog():Promise<string>;
