// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DomReady(arg1) {
  return window['go']['gui']['App']['DomReady'](arg1);
}

export function GetServerUrl() {
  return window['go']['gui']['App']['GetServerUrl']();
}

export function SelectDirectory() {
  return window['go']['gui']['App']['SelectDirectory']();
}

export function SelectImageFile() {
  return window['go']['gui']['App']['SelectImageFile']();
}

export function SelectMultipleImageFile() {
  return window['go']['gui']['App']['SelectMultipleImageFile']();
}
